name: Actual Budget
version: "1.0"
slug: actual_budget
description: "Actual Budget Add-on f√ºr Home Assistant auf Raspberry Pi 4"
arch:
  - armv7
  - armhf
  - aarch64
startup: "services"
boot: "auto"
ports:
  3000/tcp: 3000
map:
  config: /config/actual_budget
options:
  db_path: "/config/actual_budget/data"
  port: 3000
